pipeline:
 run-server-tests:
    image: node:8.9
    detach: true
    commands:
       - cd ./server
       - sh ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [ pull_request ]

 run-client-tests:
    image: node:8.9
    commands:
      - cd ./client
      - sh ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [ pull_request ]

 npm-release-new-version:
    image: plugins/npm
    secrets: [ npm_username, npm_email, npm_password ]
    folder: ./client/
    when:
      event: [ tag ]
      branches: [ master ]

 docker-release-new-version:
    image: plugins/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tags:
      - $DRONE_TAG
      - latest
    repo: paralect/pdf-service
    dockerfile: ./server/Dockerfile
    context: ./server
    secrets: [ docker_password, docker_email, docker_username ]
    when:
       event: [ tag ]
       branches: [ master ]

services:
  pdf-service:
    image: paralect/pdf-service

branches: [ master, "*:master" ]