version: '2'

services:
  pdf-service:
    build:
      context: "./"
      dockerfile: Dockerfile
    volumes:
      - "./src:/app/src"
    environment:
      - DEBUG=true
    ports:
      - "4444:3000"
